[programs.localnet]
mysolanaapp = "9Mbjs3YuRtKMmhpoAzHfvb2GxySrTLpdTqoV33GuWihH"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/bill/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
